# Generated by Django 3.2.5 on 2021-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Phone_Number', models.BigIntegerField()),
                ('problem', models.TextField()),
                ('Time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Lab_img', models.ImageField(upload_to='pics')),
                ('Pharmacy_img', models.ImageField(upload_to='pics')),
                ('equipments_img1', models.ImageField(upload_to='pics')),
                ('equipments_img2', models.ImageField(upload_to='pics')),
                ('number', models.BigIntegerField()),
                ('add', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(choices=[(1, 'Anantapur'), (2, 'Chittoor'), (3, 'East Godavari'), (4, 'Guntur'), (5, 'YSR Kadapa'), (6, 'Krishna'), (7, 'Kurnool'), (8, 'Nellore'), (9, 'Prakasam'), (10, 'Srikakulam'), (11, 'Vijayanagaram'), (12, 'Visakapatnam'), (13, 'West Godavari')], max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('Phone_Number', models.PositiveBigIntegerField()),
                ('order', models.TextField()),
            ],
        ),
    ]
