# Generated by Django 3.2.5 on 2021-07-29 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sent_Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
