# Generated by Django 3.2.5 on 2021-07-29 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
