# Generated by Django 3.2.5 on 2021-07-29 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Sent_Time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
