# Generated by Django 3.2.5 on 2021-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_appointment_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
