# Generated by Django 3.2.5 on 2021-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
