# Generated by Django 3.2.5 on 2021-08-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modify',
            name='Lab_img',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='Pharmacy_img',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='equipments_img1',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='equipments_img2',
        ),
    ]
