# Generated by Django 3.2.5 on 2021-08-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210808_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='pics')),
                ('Product', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
