# Generated by Django 3.2.5 on 2021-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.CharField(max_length=255),
        ),
    ]
