# Generated by Django 3.2.5 on 2021-08-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_cart_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_item',
        ),
    ]
