# Generated by Django 3.2.5 on 2021-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_cart_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='Total',
            field=models.FloatField(),
        ),
    ]
